site_name: rue
theme: 'material'

copyright: 'Copyright &copy; 2017 - 2018 Martin Crawford'

pages:
    - Home: index.md
    - User Guide:
      - Getting Started: 'user-guide/getting-started.md'
      - Injection Patterns: 'user-guide/injection-patterns.md'
      - Activation Profiles: 'user-guide/activation-profiles.md'
      - Dependency Notation: 'user-guide/dependency-notation.md'
      - Lifecycle Functions: 'user-guide/lifecycle-functions.md'
      - Test Container: 'user-guide/test-container.md'
    - Reference:
      - 'All': 'reference/index.md'
      - 'Modules':
        - 'rue': 'reference/module-rue.md'
      - 'Classes':
        - 'Builder': 'reference/class-builder.md'
        - 'Container': 'reference/class-container.md'
        - 'Environment': 'reference/class-environment.md'
        - 'FactoryBuilder': 'reference/class-factory-builder.md'
        - 'ModuleBuilder': 'reference/class-module-builder.md'
        - 'ServiceBuilder': 'reference/class-service-builder.md'
        - 'TestContainer': 'reference/class-test-container.md'
    - License: license.md

extra:
  palette:
    - primary: 'deep purple'
    - accent: 'teal'
  social:
    - type: 'github'
      link: 'https://github.com/bemisguided/rue'
  feature:
      tabs: true

markdown_extensions:
  - admonition
  - footnotes
  - codehilite(linenums=true)
  - toc(permalink=true)
