site_name: rue
#theme: readthedocs
theme: 'material'
#theme_dir: '../mkdocs-material/material'

copyright: 'Copyright &copy; 2017 - 2018 Martin Crawford'

pages:
    - Home: index.md
    - User Guide:
      - Getting Started: 'user-guide/getting-started.md'
      - Injection Patterns: 'user-guide/injection-patterns.md'
      - Activation Profiles: 'user-guide/activation-profiles.md'
      - Dependency Notation: 'user-guide/dependency-notation.md'
      - Lifecycle Functions: 'user-guide/lifecycle-functions.md'
      - Test Container: 'user-guide/test-container.md'
    - Reference:
      - 'rue.factory()': 'reference/rue-factory.md'
      - 'rue.module()': 'reference/rue-module.md'
      - 'rue.service()': 'reference/rue-service.md'
      - 'class Builder': 'reference/class-builder.md'
      - 'class FactoryBuilder': 'reference/class-factory-builder.md'
      - 'class ModuleBuilder': 'reference/class-module-builder.md'
      - 'class ServiceBuilder': 'reference/class-service-builder.md'

extra:
  palette:
    - primary: 'deep purple'
    - accent: 'teal'
  social:
    - type: 'github'
      link: 'https://github.com/bemisguided/rue'
  feature:
      tabs: true

markdown_extensions:
  - admonition
  - footnotes
  - codehilite(linenums=true)
  - toc(permalink=true)
